# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b945df003b62f1fa9b56c68ab6bb199f6373ca189e528c7c8bfce3496fb7ed9ecdbdf9031466d01bf5a9442e0523eff26139ec03ce6c414c91f46b0a9ce9d38a

test:
  secret_key_base: dc84e2c4912bb870fbb3bc3949e36a1cda6d758ca10963d1acfe3e845a09ecb13df27814fd053df3dd0ef31c81eba25107fac42879e61fab48c420e5cfb8f9a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
